### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ckn123** [lallubharteja/kws_scripts#2]
I don't quite understand the methods you have given. Can you give me a basic demo, thank you!

**Comment by lallubharteja** [comment]
Could you be more specific as to which method you are referring to?

**Comment by ckn123** [comment]
> 您可以更具体地说明您指的是哪种方法？

I looked at the example given by kaldi/bable, but I don't quite understand how to connect ASR with kws. I want to create a small example, such as doing an example of a keyword on TIMTI.

**Comment by ckn123** [comment]
> 您可以更具体地说明您指的是哪种方法？

Since I found the most basic demo on the Internet, I really don't quite understand how to get started. I am writing a master's thesis, but for the experiment I don't know how to use the KWS experiment. Can you guide me? Thank you!

**Comment by lallubharteja** [comment]
Assuming you have a kaldi-based ASR setup, you need three files for setting up your KWS system
- ecf file
- keyword list
- rttm file

Have you tried creating these already? This is also described in: http://kaldi-asr.org/doc/kws.html
You can create each of these files using the commands given in this repo.

**Comment by ckn123** [comment]
> 假设您有基于kaldi的ASR设置，则需要三个文件来设置KWS系统
> 
> * ecf文件
> * 关键字列表
> * rttm文件
> 
> 你有没有试过创建这些？这也在以下描述：[http](http://kaldi-asr.org/doc/kws.html)：[//kaldi-asr.org/doc/kws.html](http://kaldi-asr.org/doc/kws.html)
> 您可以使用此repo中给出的命令创建每个文件。



> 假设您有基于kaldi的ASR设置，则需要三个文件来设置KWS系统
> 
> * ecf文件
> * 关键字列表
> * rttm文件
> 
> 你有没有试过创建这些？这也在以下描述：[http](http://kaldi-asr.org/doc/kws.html)：[//kaldi-asr.org/doc/kws.html](http://kaldi-asr.org/doc/kws.html)
> 您可以使用此repo中给出的命令创建每个文件。


> 假设您有基于kaldi的ASR设置，则需要三个文件来设置KWS系统
> 
> * ecf文件
> * 关键字列表
> * rttm文件
> 
> 你有没有试过创建这些？这也在以下描述：[http](http://kaldi-asr.org/doc/kws.html)：[//kaldi-asr.org/doc/kws.html](http://kaldi-asr.org/doc/kws.html)
> 您可以使用此repo中给出的命令创建每个文件。

My kaldi ASR model is kaldi/egs/thchs30.
I created exf.xml according to the command given by your repro, and I created kwlist.xml manually. However, for rttm I don't know how to create it.

**Comment by ckn123** [comment]
> Could you be more specific as to which method you are referring to?

I know that you are very busy, can you tell me your email address? This way I have a problem and can email you very quickly.

**Comment by lallubharteja** [comment]
To create the rttm, you can use the script create_rttm.sh. It has two steps, first to create "ali" directory and then create rttm file from it.

to create "ali" dir: you will need set two inputs in the create_rttm.sh file: 
$feats and  $lang. $feats is the location of the audio features and related files generated from the dataset search on. $lang is the directory where your L.fst is generated. 

I would prefer to answer your queries, as it might help somebody else as well. If you want you can obtain my email from my webpage mittulsingh.com

**Comment by ckn123** [comment]
> To create the rttm, you can use the script create_rttm.sh. It has two steps, first to create "ali" directory and then create rttm file from it.
> 
> to create "ali" dir: you will need set two inputs in the create_rttm.sh file:
> $feats and $lang. $feats is the location of the audio features and related files generated from the dataset search on. $lang is the directory where your L.fst is generated.
> 
> I would prefer to answer your queries, as it might help somebody else as well. If you want you can obtain my email from my webpage mittulsingh.com

What is the role of .common/slurm_dep_graph.sh in create_rttm.sh, I didn't find this file

**Comment by lallubharteja** [comment]
You can find this file below, this is used to run jobs onto a cluster managed using slurm utility. https://github.com/psmit/kaldi-recipes/blob/master/common/slurm_dep_graph.sh

You can choose to remove this script as well and edit the create_rttm.sh script accordingly.

**Comment by ckn123** [comment]
The rrtm file generated by running ali_to_rttm.sh in your report is blank.
I don't know how to start editing and re-editing create_rttm.sh

**Comment by ckn123** [comment]
If you are not busy right now, can you remotely operate my computer through the teamViewer software?

**Comment by lallubharteja** [comment]
Sorry, my connection is slow to be able to do that. What does your log/L_align.log say? This log folder will exist in the folder you got your rttm.

**Comment by ckn123** [comment]
FATAL: FstCompiler: Symbol "data/lang/local//lexicon.txt" is not mapped to any integer arc ilabel, symbol table = data/lang/phones.txt, source = standard input, line = 4
ERROR: FstHeader::Read: Bad FST header: standard input

**Comment by ckn123** [comment]
My command input is    sudo kws_scripts/ali_to_rttm.sh data/train data/lang exp/tri4b_dnn_ali

**Comment by lallubharteja** [comment]
Seems like the file data/lang/phones.txt is in an incorrect format, specifically line 4. Hopefully, using the correct version of this file will correct the error. I must say I can only with the problems related to kws_scripts. ali_to_rttm.sh happens to be a Kaldi repo file and is included in this repo just as an example. I would suggest posting to Kaldi help forum if the issue persists.

**Comment by ckn123** [comment]
Maybe my data set is Chinese, so I can't match it.

**Comment by lallubharteja** [comment]
I would think not think that to be the case. For now, closing this issue.

**Comment by l2009312042** [comment]
@ckn123   i have meet the same question as you ,and i have solved it  .
the key is  in file  ali_to_rttm.sh   make_L_align.sh have 3 paras,the fisrt param should be  data/local/lang_tmp !!!!
