### ISSUE TITLE
ECF creation error

### ISSUE THREAD

**Issue by boleamol** [lallubharteja/kws_scripts#3]
Whenever I am trying to build ECF file getting following error..

amol@amol-HP-406-G1-MT:/media/amol/data/speech_kws_2$ ./create_ecf_file.sh data/test/wav.scp data/test/ecf.xml
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
amol@amol-HP-406-G1-MT:/media/amol/data/speech_kws_2$ 

May I know what is reason for this?

**Comment by lallubharteja** [comment]
Try again by cloning a new version. I just pushed some updates. Also, the
scripts assume that Kaldi c++ tools are in your path.

**Comment by boleamol** [comment]
Cloned new version, also Kaldi is in path. Again same error.

amol@amol-HP-406-G1-MT:/media/amol/data/speech_kws_2$ ./create_ecf_file.sh data/test/wav.scp data/test/ecf.xml
wav-to-duration scp:data/test/wav.scp ark,t:- 
LOG (wav-to-duration[5.5.85~3-024d1]:main():wav-to-duration.cc:92) Printed duration for 500 audio files.
LOG (wav-to-duration[5.5.85~3-024d1]:main():wav-to-duration.cc:94) Mean duration was 3.99352, min and max durations were 3.52, 4.08
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
syntax error at -e line 1, at EOF

**Comment by lallubharteja** [comment]
could you paste the output of your data/test/dur.txt?

**Comment by boleamol** [comment]
dur.txt is generated.. which content are as below ...
audio_1026_2015_07_22-03_13 4 
audio_1026_2015_07_23-05_32 4 
audio_1026_2015_07_23-10_49 4 
audio_1026_2015_07_24-02_37 4 
audio_1026_2015_07_24-03_42 4.02 
audio_1026_2015_07_24-06_14 4 
audio_1026_2015_07_24-06_28 4.04 
audio_1026_2015_07_24-12_53 4 
audio_1026_2015_07_27-02_47 4 
audio_1026_2015_07_28-01_00 4 
audio_1026_2015_07_28-02_23 4


create_ecf_file.sh  calculated duration for all files which present in wav.scp without any errors.

**Comment by boleamol** [comment]
It is Generating ecf file also, I attached here
[ecf.xml.txt](https://github.com/lallubharteja/KWS-Scripts/files/2896534/ecf.xml.txt)



I am new in kaldi, so I don't know exact format of ecf file.
It was not accepting .xml file so I added .txt
